apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: fleet-simple-app
spec:
    rules:
    - host: hpa.lvh.me
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            serviceName: fleet-simple-app
            servicePort: 8080