defaultNamespace: fleet-sample
diff:
  comparePatches:
  - apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    name: fleet-simple-app
    operations:
    - {"op":"replace", "path":"/spec/rules/0/hots", "value":"hpa.lvh.me"}
